### ISSUE TITLE
NTLM needs domain\username and a password when -no-pass is set

### ISSUE THREAD

**Issue by embargod** [dirkjanm/BloodHound.py#168]
Description: When using exported `KRB5CCNAME` with `bloodhound.py` i got this error also it asks `Password` when `-no-pass` is set. Even with `netexec` same issue (sorry for offtop)

When `LDAPS channel binding is enabled` its throws the error 
When `LDAPS channel binding is not enabled` i can pass anything in `Password:` input and it will continue 
Looks like the problem is in ldap channel binding/signing?

But `Password:` and `-no-pass` looks like something weird

Error: `ldap3.core.exceptions.LDAPUnknownAuthenticationMethodError: NTLM needs domain\username and a password`

Screenshot:
LDAPS channel binding is enabled
![image](https://github.com/dirkjanm/BloodHound.py/assets/62397547/f1903119-d9b5-458a-a511-c3dd7d009639)

LDAPS channel binding is not enabled
![image](https://github.com/dirkjanm/BloodHound.py/assets/62397547/0cbfd4c7-5c90-49a5-b7cb-be932452a925)

`nxc` in both ways throws `Error: ldap3.core.exceptions.LDAPUnknownAuthenticationMethodError: NTLM needs domain\username and a password`
![image](https://github.com/dirkjanm/BloodHound.py/assets/62397547/f8f59f42-035a-423a-9850-2fde7d00dcf3)
![image](https://github.com/dirkjanm/BloodHound.py/assets/62397547/70bf5afd-6d6a-4f16-b075-39d5aa316cf7)

**Comment by dirkjanm** [comment]
this should now be fixed, let me know if you continue having these issues

**Comment by vfgesay4hb** [comment]
In bloodhound-ce (even with master merged into) this is still an issue, applying the `ad/authentication.py`-part of https://github.com/deadjakk/BloodHound.py/pull/1/commits/7590dd449d5379503f9a1768e4355cbab2521f31 fixes it for me.
